INSERT INTO public.users (id, name, role) VALUES (1, 'Alice', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (2, 'Bob', 'Admin');
INSERT INTO public.users (id, name, role) VALUES (3, 'Catherine', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (4, 'David', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (5, 'Ernie', 'Retail Agent');
INSERT INTO public.users (id, name, role) VALUES (6, 'Frank', 'Retail Agent');
INSERT INTO public.users (id, name, role) VALUES (7, 'Gloria', 'Agent');
INSERT INTO public.users (id, name, role) VALUES (8, 'Harold', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (9, 'Isabella', 'Retail Agent');
INSERT INTO public.users (id, name, role) VALUES (10, 'John', 'Retail Agent');
INSERT INTO public.users (id, name, role) VALUES (11, 'Kate', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (12, 'Leonard', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (13, 'Michael', 'Admin');
INSERT INTO public.users (id, name, role) VALUES (14, 'Nicole', 'Retail Agent');
INSERT INTO public.users (id, name, role) VALUES (15, 'Oscar', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (16, 'Patricia', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (17, 'Quincy', 'Retail Agent');
INSERT INTO public.users (id, name, role) VALUES (18, 'Robert', 'Call Center Agent');
INSERT INTO public.users (id, name, role) VALUES (19, 'Sally', 'Retail Agent');
INSERT INTO public.users (id, name, role) VALUES (20, 'Ted', 'Call Center Agent');
